#
# GitHub Action for running Xygeni scanner on GitHub workflows.
#
name: 'Xygeni Scanner'
author: 'Xygeni'
description: 'Runs Xygeni Scanner'

inputs:
  token:
    description: 'API token for authentication with Xygeni platform.'
    required: true
  command:
    description: 'Command to execute by the scanner'
    required: false
    default: scan --never-fail -d $GITHUB_WORKSPACE
  gh_token:
    description: 'GitHub token to retrieve repository information for misconfigurations and compliance.'
    required: false
    default: $GITHUB_TOKEN
  xygeni_url:
    description: 'Base URL of the Xygeni API.'
    required: false
    default: 'https://api.xygeni.io'
  xygeni_dashboard_url:
    description: 'Base URL of the Xygeni Dashboard.'
    required: false
    default: 'https://in.xygeni.io/dashboard'

branding:
  color: 'green'
  icon: 'code'

runs:
  using: 'composite'
  steps:
    - name: 'Download & Install Xygeni Scanner'
      shell: bash
      run: |
        echo "Downloading Xygeni Scanner..."
        curl -sSfL https://get.xygeni.io/latest/scanner/xygeni_scanner.zip -o /tmp/xygeni_scanner.zip
        echo "Installing Xygeni Scanner to $HOME/.xygeni..."
        mkdir -p $HOME/.xygeni
        unzip -q -o /tmp/xygeni_scanner.zip -d $HOME/.xygeni
        mv $HOME/.xygeni/xygeni_scanner/* $HOME/.xygeni/
        rmdir $HOME/.xygeni/xygeni_scanner
        rm /tmp/xygeni_scanner.zip
        chmod +x $HOME/.xygeni/xygeni
        echo "Xygeni Scanner installed successfully."

    - name: 'Run Xygeni Scanner'
      shell: bash
      run: |
        echo "Running xygeni ${{ inputs.command }}" 
        $HOME/.xygeni/xygeni ${{ inputs.command }}
      env:
        XYGENI_TOKEN: ${{ inputs.token }}
        XYGENI_URL: ${{ inputs.xygeni_url }}
        XYGENI_DASHBOARD_URL: ${{ inputs.xygeni_dashboard_url }}
        GITHUB_TOKEN: ${{ inputs.gh_token }}