#
# GitHub Action for running Xygeni scanner on GitHub workflows.
#
name: 'Xygeni Scanner'
author: 'Xygeni'
description: 'Runs Xygeni Scanner'

inputs:
  xygeni_url:
    description: 'Base URL of the Xygeni API.'
    required: false
    default: 'https://api.xygeni.io'
  token:
    description: 'API token. Must be provided, or username/password as alternative.'
    required: false
    default: ''
  username:
    description: 'Username (using API token is recommended)'
    required: false
    default: ''
  password:
    description: 'Password (using API token is recommended)'
    required: false
    default: ''
  command:
    description: 'Command to execute by the scanner'
    required: false
    default: 'scan --never-fail'
  gh_token:
    description: 'GitHub token to retrieve repository information for misconfigurations and compliance.'
    required: false
    default: $GITHUB_TOKEN

branding:
  color: 'green'
  icon: 'code'

runs:
  using: 'composite'
  steps:
    - name: 'Download & Install Xygeni Scanner by using the Token'
      if: github.event.inputs.token != ''
      shell: bash
      run: curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -s ${{ inputs.xygeni_url }} -t ${{ inputs.token }}
    
    - name: 'Download & Install Xygeni Scanner by using the Basic Auth''
      if: github.event.inputs.token == ''
      shell: bash
      run: curl -L https://get.xygeni.io/latest/scanner/install.sh | /bin/bash -s -- -s ${{ inputs.xygeni_url }} -u ${{ inputs.username }} -p ${{ inputs.password }}

    - name: 'Run Xygeni Scanner'
      shell: bash
      run: $HOME/.xygeni/xygeni ${{ inputs.command }} -d ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
