#
# GitHub Action for running Xygeni scanner on GitHub workflows.
#
name: 'Xygeni Scanner'
author: 'Xygeni'
description: 'Runs Xygeni Scanner'

inputs:
  xygeni_url:
    description: 'Base URL of the Xygeni API.'
    required: false
    default: 'https://api.xygeni.io'
  token:
    description: 'API token. Must be provided, or username/password as alternative.'
    required: false
  username:
    description: 'Username (using API token is recommended)'
    required: false
  password:
    description: 'Password (using API token is recommended)'
    required: false
  command:
    description: 'Command to execute by the scanner'
    required: false
    default: 'scan -n ${{ github.repository }} -d /app'

branding:
  color: 'green'
  icon: 'code'

runs:
  using: 'composite'
  steps:
    - name: 'Download Xygeni Scanner docker image'
      shell: bash
      run: docker pull xygeni/xygeni_scanner:latest

    - name: 'Start Xygeni Scanner docker image'
      shell: bash
      run: docker run -v ${{ github.workspace }}:/app -e XYGENI_TOKEN=${{ inputs.token }} -e XYGENI_USERNAME=${{ inputs.username }} -e XYGENI_PASSWORD=${{ inputs.password }} -e XYGENI_SERVER=${{ inputs.xygeni_url }} -t xygeni/xygeni_scanner ${{ inputs.command }}
