# Commented for now because scanner is not renamed yet
#on: push
on: workflow_dispatch

jobs:
  scan-test:
    runs-on: ubuntu-latest
    name: xygeni-github-action

    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744

      - name: Scanner
        uses: ./ # Uses an action in the root directory
        id: Scanner
        with:
          username: ${{ secrets.SEC_U }}
          password: ${{ secrets.SEC_P }}
          # token: ${{ secrets.XYGENI_TOKEN }}
          # Only for testing
          xygeni_url: 'https://apidev.xygeni.io/deps-doctor-service'
