# This workflow will execute xygeni scanner deployed in the LabDev environment on demand.
# Reports will be uploaded with the user nicolas.carmona+dogfooding@xygeni.io

name: Testing

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  xygeni-scan:
  
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Xygeni-Scanner-LabDev
      uses: xygeni/xygeni-action@4e94e5ea737f5ebfedac8b1a5b75d8c60c21932d
      id: Xygeni-Scanner
      with:
        command: scan --never-fail -o ./XygeniAction.json -f json
        token: ${{ secrets.XYGENI_TOKEN_LABDEV }}
        gh_token: ${{ secrets.GH_PAT_FOR_DOGFOODING }}
        xygeni_url: https://apidev.xygeni.io/deps-doctor-service
    - name: Upload scan report result (deps)
      uses: actions/upload-artifact@v3
      with:
          name: deps.XygeniAction.json
          path: ./deps.XygeniAction.json
          retention-days: 1
    - name: Upload scan report result (suspectdeps)
      uses: actions/upload-artifact@v3
      with:
          name: suspectdeps.XygeniAction.json
          path: ./suspectdeps.XygeniAction.json
          retention-days: 1
    - name: Upload scan report result (secrets)
      uses: actions/upload-artifact@v3
      with:
          name: secrets.XygeniAction.json
          path: ./secrets.XygeniAction.json
          retention-days: 1
    - name: Upload scan report result (misconf)
      uses: actions/upload-artifact@v3
      with:
          name: misconf.XygeniAction.json
          path: ./misconf.XygeniAction.json
          retention-days: 1
    - name: Upload scan report result (iac)
      uses: actions/upload-artifact@v3
      with:
          name: iac.XygeniAction.json
          path: ./iac.XygeniAction.json
          retention-days: 1
